### ISSUE TITLE
Network Indicator does not work

### ISSUE THREAD

**Issue by mmeissner** [0ry0n/Resource_Monitor#1]
**Describe the bug**
Network indicator stays all time on 0 upload/download

**Expected behavior**
Network indicator shows real up/down bandwidth

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Extension expects a specific output format from '/proc/net/dev' that is not present on my system. 

### Format on my System
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
enp3s0: 1422819    3433    0    0    0     0          0         7   645340    3391    0    0    0     0       0          0
  tun0:  888265    1774    0    0    0     0          0         0   258858    1861    0    0    0     0       0          0
enp0s31f6:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
    lo:   36892     474    0    0    0     0          0         0    36892     474    0    0    0     0       0          0
wlp4s0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0

**Comment by 0ry0n** [comment]
Fixed. Thanks for collaboration.
