### ISSUE TITLE
extension showing nothing

### ISSUE THREAD

**Issue by wahyufadz** [0ry0n/Resource_Monitor#10]
**Describe the bug**
extention showing three dots instead of pecentage

**Screenshots**
![Screenshot from 2020-05-05 11-12-29](https://user-images.githubusercontent.com/10463782/81034608-e92b9000-8ec1-11ea-8930-51e38dcfd1e7.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 freshly installed

**Additional context**
i use hiDPI laptop with 4k display

**Comment by 0ry0n** [comment]
Hi, thanks for the report. Have you tried changing the width from prefs?

**Comment by FieserKiller** [comment]
same for me. 15.6" OLED with 3840x2160 resolution. No values, only 3 dots, even with max width of 40.

**Comment by 0ry0n** [comment]
Download the gnome-3.34 branch and try it, increase the width and give me feedback. thanks!

**Comment by wahyufadz** [comment]
i have tried to change but nothing happened

**Comment by wahyufadz** [comment]
> Download the gnome-3.34 branch and try it, increase the width and give me feedback. thanks!

i've try it and the issue still exist

**Comment by 0ry0n** [comment]
> > Download the gnome-3.34 branch and try it, increase the width and give me feedback. thanks!
> 
> i've try it and the issue still exist

Try again now... I changed px to em in the gnome-3.34 branch

**Comment by wahyufadz** [comment]
sorry it's still same here

**Comment by pvanhemmen** [comment]
I have the same issue here. Like @FieserKiller I'm also on a hdpi display with 3840x2160 resolution and display scaling set to 200%. When I set it to 100% all figures are displayed correctly. So it seems the extension's width units are not converted correctly for scaled display settings.

**Comment by 0ry0n** [comment]
Fixed in release 16.
