### ISSUE TITLE
Add an option to disable Gnome system monitor start when click on extension

### ISSUE THREAD

**Issue by brunetton** [0ry0n/Resource_Monitor#14]
**Is your feature request related to a problem? Please describe.**
I installed it for novices and they are quite annoyed by the fact that Gnome system monitor is started when they click on the extension.

**Describe the solution you'd like**
I'd like an option to disable this behavior 

**Describe alternatives you've considered**
I don't think there are alternatives

**Comment by 0ry0n** [comment]
Added in next update (release 10). Thanks for collaboration.

**Comment by brunetton** [comment]
This is great ! Thanks a lot
