### ISSUE TITLE
[Request] Show disk space usage

### ISSUE THREAD

**Issue by herrenP** [0ry0n/Resource_Monitor#17]
I cannot see that the extension show disk space usage. It seems to only show the IO for disk. Is this something you will consider adding?

If so, would it be possible to maybe choose from mounts instead of disks or both? In my case I want to monitor a remote system and I figured I could mount the remote system locally and choose that mount in your extension. I guess if we could add labels to the chosen mounts/disks would be pretty nice as well.

**Comment by 0ry0n** [comment]
See the next update.
