### ISSUE TITLE
Better icons

### ISSUE THREAD

**Issue by marcelklehr** [0ry0n/Resource_Monitor#19]
**Is your feature request related to a problem? Please describe.**
The icons used are not really ideal.

**Describe the solution you'd like**
Use different icons for CPU and RAM at least.

**Additional context**
I actually took the time to search for a list of GTK icons and the ones you used really do come closest, but I think it would be better to ship custom icons instead. There's nice websites nowadays with royalty free icons.

Thanks for considering! Otherwise this is a top extension :heart:

**Comment by 0ry0n** [comment]
Thanks :heart: See the next update.
