### ISSUE TITLE
Doesn't work with gnome-shell 3.32

### ISSUE THREAD

**Issue by BloodyIron** [0ry0n/Resource_Monitor#2]
Hey, if you could update this to work with gnome-shell 3.32 that'd be great. Namely since this is the version shipping with Ubuntu 19.04.

**Comment by 0ry0n** [comment]
After installation from GNOME, try to run:

sudo cp ~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/schemas/com.github.Ory0n.Resource_Monitor.gschema.xml /usr/share/glib-2.0/schemas && sudo glib-compile-schemas /usr/share/glib-2.0/schemas

and restart GNOME Shell.

**Comment by 0ry0n** [comment]
Updated
