### ISSUE TITLE
Extension broke after update

### ISSUE THREAD

**Issue by pktiuk** [0ry0n/Resource_Monitor#20]
**Describe the bug**
Extension is inactive and I am not able to use it.

**To Reproduce**
Update this extension to the latest version.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45544416/104603585-da19f600-567c-11eb-88b3-0c69ccf8895f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Error visible when I tried to open preferences window in gnome tweaks:
```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/pawelkot/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/prefs.js:29:3
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

**Comment by 0ry0n** [comment]
See the next update.
