### ISSUE TITLE
Gnome 40 support and Bps network unit

### ISSUE THREAD

**Issue by Digitalone1** [0ry0n/Resource_Monitor#27]
Hello, thanks for this extension, I use it on Arch to see CPU, RAM and net usage real time.

I'd like to know if it will work on Gnome 40 since the new shell version is coming upstream for the new update.

And I'd like to recommend a new feature. Give an option to show network traffic in Bit/s rather than Byte/s.

Thanks and good work.

**Comment by Digitalone1** [comment]
Updated to Gnome 40. Not working.

**Comment by 0ry0n** [comment]
Hi, thanks for use this extension. Temporarily you can use the version in the gnome-40.0 branch but pref still doesn't work.
You will have to wait for the update.

**Comment by 0ry0n** [comment]
The new version [15](https://github.com/0ry0n/Resource_Monitor/releases/tag/15) compatible with GNOME Shell 40 is now available on GNOME Extensions.

**Comment by Digitalone1** [comment]
Thank you, I already installed it on Arch (I had to make a custom PKGBUILD since it's not going to be updated on AUR). It's working without issues.

Anyway I would leave this ticket open for the implementation of Bit/s speed unit for network indicator in the future. Now I'm using [netspeedsimplified](https://github.com/prateekmedia/netspeedsimplified) as network monitor.

**Comment by 0ry0n** [comment]
Added functionality. Thanks for cooperating.

**Comment by Digitalone1** [comment]
I'm trying it, but unfortunately it has graphical glitch. :(
