### ISSUE TITLE
Settings window error.

### ISSUE THREAD

**Issue by ErudonZ** [0ry0n/Resource_Monitor#3]
I installed from the On/Off switch from extensions.gnome.org, installation went fine with no errors, but when I try to open the settings window I get an error, "something went wrong", the technical details :
"
TypeError: settings is undefined

Stack trace:
  PatternsPrefs@/home/zeon/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/prefs.js:111:3
  buildPrefsWidget@/home/zeon/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/prefs.js:298:16
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43
"
I can see the information on my taskbar no problem, but I can't open the settings.

**Comment by 0ry0n** [comment]
Fixed in the next update (release 6).
