### ISSUE TITLE
gnome shell warnings in journal

### ISSUE THREAD

**Issue by anno0** [0ry0n/Resource_Monitor#30]
**Describe the bug**
Often I see the following message in journal log. I attached the log snippet.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 20.04
 - Gnome: 3.36.8

**Additional context**
[deprecated.txt](https://github.com/0ry0n/Resource_Monitor/files/6722160/deprecated.txt)

**Comment by tswaehn** [comment]
looks similar to my case 

```
Nov 25 11:02:13 debian64 gnome-shell[6035]: JS ERROR: Error: Error: df: /run/user/1000/doc: Operation not permitted
                                            
                                            _refreshDiskSpace/<@/home/tswaehn/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/extension.js:1201:23
Nov 25 11:02:15 debian64 gnome-shell[6035]: JS ERROR: Error: Error: df: /run/user/1000/doc: Operation not permitted
```
                                           
for some reason this extension tries to get the diskspace of an empty folder. this may be unintentional and should be 
```
df /run/user/1000 
```
instead of 
```
df /run/user/1000/doc
```


this is a nice extension. but need to uninstall because of that :(

**Comment by 0ry0n** [comment]
@anno0  thanks for reporting. It has been fixed in the later version 38b21e1d43b9c6e6216fe2b6b49eef47730dfa86.

**Comment by 0ry0n** [comment]
@tswaehn thanks for reporting. Please tell me which version of GNOME you are using, because the error is different from that of @anno0. Thanks.

**Comment by tswaehn** [comment]
Iam using gnome 40

**Comment by 0ry0n** [comment]
Fixed in release 16.
