### ISSUE TITLE
RAM usage is well below that shown in System Monitor

### ISSUE THREAD

**Issue by jcreek** [0ry0n/Resource_Monitor#4]
**Describe the bug**
The extension shows a significantly lower RAM usage than System Monitor, e.g. 45% rather than 53.5%. 

**To Reproduce**
I installed the extension from https://extensions.gnome.org/extension/1634/resource-monitor/ on Ubuntu 19.04. 

**Expected behavior**
I would expect the two to either show the same values or be within 1% of each other.

**Comment by 0ry0n** [comment]
The data is different because it is calculated differently.
Mine is: (Memory) total - free + buffers + cached
while gnome i think does: (Memory) total - available

**Comment by sitnarf** [comment]
> The data is different because it is calculated differently.
> Mine is: (Memory) total - free + buffers + cached
> while gnome i think does: (Memory) total - available

@Ory0n Do you mean that yours is:  total - (free + buffers + cached)? Could you please elaborate what the difference in calculation practically means for the user?
