### ISSUE TITLE
Unable to get preferences on Ubuntu 20.04 dev

### ISSUE THREAD

**Issue by isbm** [0ry0n/Resource_Monitor#7]
**Describe the bug**
No way to get to the preferences

**To Reproduce**
Extension works, but no matter where you click on it, you get only system monitor. The widths are shrank and I see only icons and dots. No idea how to change that.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 development

**Comment by 0ry0n** [comment]
Please use gnome-tweak or extensions (gnome-shell-extension-prefs) to get extension preferences.

**Comment by porridge** [comment]
Took me a while to find that preferences are accessible through gnome tweak tool, would be great if you could mention this in the README.
Thanks for this nice program!
